version: "3.7"

services:
  algo:
    build:
      context: .
    image: ghcr.io/mosesmc52/etf-trend-rp-vt:${TAG:-latest}
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env:ro
    dns:
      - 8.8.8.8
      - 1.1.1.1
